export const GET_MUSIC_ALBUMS = 'GET_MUSIC_ALBUMS';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const RENAME_PLAYLIST = 'RENAME_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
